TC_004.002.002 | Sign in & Registration, Account >Sign in_(accessibility of the form) > Check an authorization form after clicking on the 'Sign in' link
RedRoverSchool/LumaProjectPython_2024_spring pull request #172
Opened 2024-05-21 04:39 UTC by egorandrew

<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;3HU9j6R7">TC_004.002.002 | Sign in &amp; Registration, Account &gt;Sign in_(accessibility of the form) &gt; Check an authorization form after clicking on the &#39;Sign in&#39; link</a></blockquote>

2024-05-21 05:14 UTC, egorandrew commented
![](https://github.trello.services/images/mini-trello-icon.png) [TC_004.002.002 | Sign in & Registration, Account >Sign in_(accessibility of the form) > Check an authorization form after clicking on the 'Sign in' link](https://trello.com/c/3HU9j6R7/410-tc004002002-sign-in-registration-account-sign-inaccessibility-of-the-form-check-an-authorization-form-after-clicking-on-the-sign)

2024-05-21 06:19 UTC, JuliaKuznetsovaQA approved these changes

2024-05-21 06:35 UTC, aqaestuser requested changes
хорошо бы исправить

2024-05-21 06:35 UTC, aqaestuser commented on tests/test_check_authorization_page.py
> +        main_page = MainPage(browser=browser)
без классов

2024-05-21 06:35 UTC, aqaestuser commented on tests/test_check_authorization_page.py
> +        sign_in.new_customers_blog("New Customers")
что делают эти методы? зачем blog?

2024-05-21 06:35 UTC, aqaestuser commented on tests/test_check_authorization_page.py
> +class TestAuthorizationPage:
тут тоже не сильно понятно зачем тестовый класс нужен

2024-05-26 09:50 UTC, egorandrew commented
CI падает из-за теста test_discount_four_tees_for_different_model_is_applies
Мой тест проходит успешно.

2024-06-02 09:48 UTC, Impyls95 approved these changes

2024-06-02 09:49 UTC, egorandrew commented on tests/test_check_authorization_page.py
> +        main_page = MainPage(browser=browser)
исправлено

2024-06-02 09:49 UTC, egorandrew commented on tests/test_check_authorization_page.py
> +        sign_in.new_customers_blog("New Customers")
исправлено

2024-06-02 09:50 UTC, egorandrew commented on tests/test_check_authorization_page.py
> +class TestAuthorizationPage:
исправлено

2024-06-02 09:51 UTC, egorandrew reviewed
исправлено

2024-06-02 10:13 UTC, egorandrew commented
Внес все предложенные изменения. Делаю PR, в CI не проходит тест не из моего PR test_verify_sorting_product_cards_by_name, локально данный тест проходит. Подскажите как разрешить данную проблему.

2024-06-12 05:51 UTC, closed without merging