TC_014.003.002 | Wish list > Removing items
RedRoverSchool/LumaProjectPython_2024_spring pull request #69
Opened 2024-05-04 17:54 UTC by vguliakin

https://trello.com/c/xP2eIJZq

2024-05-04 18:01 UTC, vguliakin commented
![](https://github.trello.services/images/mini-trello-icon.png) [TC_014.003.002 | Wish list > Removing items](https://trello.com/c/xP2eIJZq/161-tc014003002-wish-list-removing-items)

2024-05-04 19:22 UTC, aqaestuser commented on pages/wish_list.py
> +__REMOVE_ITEM = "//div[@class='product-item-actions']/a[@class='btn-remove action delete']"
почему url а не __url ?

2024-05-04 19:27 UTC, vguliakin commented on pages/wish_list.py
> +__REMOVE_ITEM = "//div[@class='product-item-actions']/a[@class='btn-remove action delete']"
Просмотрел это
Тогда вопрос оставлять __ или мне их убрать

2024-05-05 12:26 UTC, AnastasiyaLugovskaya requested changes

2024-05-05 12:26 UTC, AnastasiyaLugovskaya commented on tests/test_wish_list.py
> +        wish_list.is_item_removed()
As I can see in your TC, the expected result is "The deleted item is not displayed in wish list". But your method is checking a success message appearance. According to the expected result in  TC, isn't it required to check that the removed item isn't displayed anymore?

2024-05-05 12:56 UTC, vguliakin commented on tests/test_wish_list.py
> +        wish_list.is_item_removed()
Changed the behavior. It now checks a name of an item

2024-05-05 13:19 UTC, AnastasiyaLugovskaya commented on tests/test_wish_list.py
> +        wish_list.is_item_removed()
If you've deleted an item with the method " wish_list.remove_item()", how this item will be found in wish list with  method "item_title = browser.driver.find_element(By.XPATH, ITEM_TITLE).text"? Won't it rise an exception, when the item isn't found?  It doesn't seem like this method checks that the deleted one particularly isn't displayed on the page. 
The test still doesn't math the 5th step in your TC and the expected result. Correct me, if I didn't catch your idea

2024-05-05 14:09 UTC, vguliakin commented on tests/test_wish_list.py
> +        wish_list.is_item_removed()
I may have misunderstood exactly how I'm supposed to find an element on a page. 

"Won't it rise an exception, when the item isn't found?" - That will be consider that we didn't find the element or what did you mean ?
"It doesn't seem that this method checks that the deleted one particularly isn't displayed on the page." - Again, how displaying or not displaying of item gonna be checked? I think we check the item by name or any other attributes.

2024-05-05 14:26 UTC, AnastasiyaLugovskaya commented on tests/test_wish_list.py
> +        wish_list.is_item_removed()
I expected something similar to _s(ITEM_TITLE).should_not_be(visible)_, so that it is clear, what the method does. What is the purpose to check text in the element that isn't supposed to be on the page? ( _s(ITEM_TITLE).should(have.text(item_title))_ - 44th line in  the wish_list.py)

2024-05-05 14:48 UTC, vguliakin commented on tests/test_wish_list.py
> +        wish_list.is_item_removed()
Fixed it. Look it up again please

2024-05-05 14:51 UTC, AnastasiyaLugovskaya approved these changes

2024-05-05 17:28 UTC, alfiyaGumar approved these changes

2024-05-05 18:29 UTC, aqaestuser approved these changes
LGTM

2024-05-05 18:32 UTC, merged